= *.vimrc* File Creation for Ansible and other Courses

This repository will create a custom VIMRC file for editing YAML files. It will add some Syntax checking and will make it look similar to VSCode for editing files. The playbook provided will install a few plugins for VIM as well as configure the plugins.

By default, line numbers, YAML linting, and column guides will be turned on. It will also have an underline following the cursor enabled by default for YAML files.

.*.vimrc* Sample
[source,bash]
----
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 nu expandtab cursorline
----

== Controlling the Plugins

You must be in command-mode in VIM to change the settings and control how VIM works.

* Turning on/off Line numbers

.Turn off Line Numbers
[source,bash]
----
:set nonu
----

.Turn on Line Numbers
[source,bash]
----
:set nu
----

* Turning on/off Column/Indention Guides

.Toggle on/off Column/Indention Guides
[source,bash]
----
:IndentLinesToggle
----

* Turn on/off Whitespace at End-of-Line (EOL)
+
.Toggle on Whitespace at EOL
[source,bash]
----
:set list
----
+
.Toggle off Whitespace at EOL
[source,bash]
----
:set nolist
----

* Turn on/off Cursor Line
+
.Toggle on Cursor Line
[source,bash]
----
:set cursorline
----
+
.Toggle off Cursor Line
[source,bash]
----
:set nocursorline
----

* Setting Color Column Guides
+
.Toggle on Color Column Guides
[source,bash]
----
:set cc=3,5,7,9,11,13,15
----
+
.Toggle off Color Column Guides
[source,bash]
----
:set cc=
----

[NOTE]
====
Plugins used have been forked to my repositories. Original repository sources can be found ...

* *ALE* - https://github.com/dense-analysis/ale
* *IndentLine (archived)* - https://github.com/Yggdroot/indentLine
* *VIM YAML Folds* https://github.com/pedrohdz/vim-yaml-folds

* https://www.arthurkoziel.com/setting-up-vim-for-yaml/

====