autocmd FileType yaml setlocal ts=2 sts=2 sw=2 nu expandtab cursorline

set foldlevelstart=20

set mouse=a  " Added for TMUX Mouse scrolling so it doesn't scroll history

let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠'
let g:ale_lint_on_text_changed = 'never'
